let mensajesFuncionales = {
    E_TRANSAC_DB: { id: 900, message: 'ERROR EN EJECUCIÓN DE TRANSACCION DE PERSISTENCIA' },
    E_PARAM_REQ: { id: 901, message: 'PARAMETROS ERRADOS O INSUFICIENTES' },
    E_CARD_INVALID_PIN_PAN: { id: 800, message: 'PAN/PIN INVALIDOS' },
    E_AUTH_CRED: { id: 700, message: 'USUARIO Y/O CONTRASEÑA INCORRECTA' },
    E_AUTH_NO_REG: { id: 701, message: 'USUARIO NO REGISTRADO' },
    E_AUTH_NO_TOKEN: { id: 702, message: 'NO SE HA INGRESADO UN TOKEN' },
    E_AUTH_NO_VALID_TOKEN: { id: 703, message: 'EL TOKEN INGRESADO NO ES VALIDO' },
    E_AUTH_NO_CORRECT_TOKEN: { id: 704, message: 'EL TOKEN NO CORRESPONDE AL CLIENTE' },
    E_USER_ALREADY_EXISTS: { id: 750, message: 'USUARIO YA REGISTRADO' },
    E_USER_NOT_EXISTS: { id: 750, message: 'USUARIO NO REGISTRADO' },
    E_ACCOUNT_BAD_NUMBER: { id: 600, message: 'NÚMERO DE CUENTA INCORRECTO' },
    E_ACCOUNT_NOT_EXIST: { id: 601, message: 'NO EXISTE EL NÚMERO DE CUENTA' },
    E_ACCOUNT_NOT_OPERATION: { id: 602, message: 'LA CUENTA NO TIENE OPERACIONES' },
    E_CUSTOMER_NOT_ACCOUNT: { id: 500, message: 'EL CLIENTE NO POSEE CUENTAS ASOCIADAS' },
    E_CUSTOMER_NOT_CARDS: { id: 501, message: 'EL CLIENTE NO POSEE TARJETAS ASOCIADAS' },
    E_CUSTOMER_NOT_OWNER: { id: 502, message: 'EL CLIENTE NO ES PROPIETARIO DEL RECURSO QUE CONSULTA' },
    E_OPERATION_NOT_OGN_ACC: { id: 400, message: 'NO EXISTE LA CUENTA ORIGEN DE OPERACION' },
    E_OPERATION_NOT_DTN_ACC: { id: 401, message: 'NO EXISTE LA CUENTA DESTINO DE OPERACION' },
    E_OPERATION_NOT_OWNER_CUSTOMER: { id: 402, message: 'EL CLIENTE NO ES DUEÑO DE LA CUENTA ORIGEN' },
    E_OPERATION_BAD_AMMOUNT: { id: 403, message: 'EL MONTO DEBE SER UN NÚMERO MAYOR A 0' },
    E_OPERATION_REQUEST_CONVERSION: { id: 404, message: 'ERROR DURANTE LA CONVERSIÓN DE MONEDA' },
    E_OPERATION_INSUFFICIENT_BALANCE: { id: 405, message: 'LA CUENTA ORIGEN NO CUENTA CON EL SALDO SUFICIENTE PARA REALIZAR LA OPERACIÓN' },
    E_OPERATION_SAME_ORIGIN_DESTINATION: { id: 406, message: 'LA CUENTA ORIGEN ES IGUAL A LA CUENTA DESTINO' },
};

module.exports = {
    mensajesFuncionales
};